
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Oct 14 00:53:14 EST 2011
//----------------------------------------------------

package logic.kb.fol.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HIGHEST = 32;
  public static final int FORALL = 31;
  public static final int UMINUS = 33;
  public static final int DOUBLE = 36;
  public static final int INTEGER = 35;
  public static final int LPAREN = 6;
  public static final int GREATER = 16;
  public static final int SEMI = 2;
  public static final int LESS = 14;
  public static final int MINUS = 34;
  public static final int RPAREN = 7;
  public static final int NOT = 20;
  public static final int AND = 19;
  public static final int OR = 21;
  public static final int BANG = 3;
  public static final int COMMA = 9;
  public static final int DIV = 22;
  public static final int PLUS = 4;
  public static final int LESSEQ = 15;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int EQUAL = 25;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int EXISTS = 30;
  public static final int MOD = 26;
  public static final int IDENT = 37;
  public static final int IMPLY = 23;
  public static final int QST = 11;
  public static final int LBRACK = 10;
  public static final int TIMES = 5;
  public static final int COLON = 12;
  public static final int RBRACK = 13;
  public static final int PFNAME = 38;
  public static final int NEQUAL = 29;
  public static final int EQUIV = 24;
  public static final int GREATEREQ = 17;
  public static final int COUNT = 18;
  public static final int FALSE = 28;
}

